12. How to remove from one array those items that exist in another?
13. How to get the positions where elements of two arrays match?
14. How to extract all numbers between a given range from a numpy array?
31. How to find the percentile scores of a numpy array?
45. How to find the most frequent value in a numpy array?
46. How to find the position of the first occurrence of a value greater than a given value?
54. How to rank items in an array using numpy?
63. How to find all the local maxima (or peaks) in a 1d array?
65. How to find the index of n'th repetition of an item in an array
67. How to compute the moving average of a numpy array?

In [1]:
import numpy as np

In [2]:
# 12.How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [3]:
# 13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [4]:
# 14. How to extract all numbers between a given range from a numpy array?

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(5<a) & (a<10)]

array([6, 9])

In [12]:
# 15. How to find the percentile scores of a numpy array?

#31-Q. Find the 5th and 95th percentile of iris's sepallength

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength,(5,95),axis=0)

array([4.6  , 7.255])

In [16]:
# 16. How to find the most frequent value in a numpy array?

#45-Q. Find the most frequent value of petal length (3rd column) in iris dataset.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
petallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[2])

In [17]:
values,counts=np.unique(petallength,return_counts=True)
freq=np.asarray((values,counts)).T

In [18]:
freq[np.argsort(freq[:,1])].shape   # (43, 2)
freq[np.argsort(freq[:,1])][42]

array([ 1.5, 14. ])

In [19]:
freq[np.argmax(counts)]   # better solution

array([ 1.5, 14. ])

In [21]:
# 17. How to find the position of the first occurrence of a value greater than a given value?

#46-Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
petalwidth = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[3])

np.asarray(np.where(petalwidth>1.0))[0][0]

50

In [23]:
# 18. How to rank items in an array using numpy?

#54-Q. Create the ranks for the given numeric array a.

np.random.seed(10)
a = np.random.randint(20, size=10)
a

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [25]:
a.argsort()  # index of acending sorted numbers 

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

In [26]:
a.argsort().argsort()+1  # ranks of acending sorted numbers

array([ 5,  3,  7,  1,  9,  8, 10,  4,  6,  2])

In [27]:
# 19. How to find all the local maxima (or peaks) in a 1d array?

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
d=np.diff(a)
a[np.where(d<0)]

array([7, 6])

In [30]:
# 20. How to find the index of n'th repetition of an item in an array

#65-Q. Find the index of 5th repetition of number 1 in x.

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x==1)

(array([ 0,  2,  3,  7,  8, 10, 11]),)

In [32]:
np.asarray(np.where(x==1))[0][4]

8

In [34]:
list(np.where(x==1))[0][4]

8

In [66]:
# Find the index of 5th repetition of number 1 in 2d array.
a=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1]).reshape(3,4)
np.array(np.where(a==1))[:,4]

array([2, 0])

In [67]:
# 21. How to compute the moving average of a numpy array?

np.random.seed(100)
m = np.random.randint(10, size=10)

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

moving_average(m,n=3).round(2)

array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])